test_seed: 42
device: "cpu"
n_envs: 32
nb_epochs: 390
epoch_steps: 512
seq_len: 8
batch_size: 128
lr: 1e-3
target_lr: 1e-6
nb_optim: 20
gamma: 0.99
gae_lambda: 0.8
clip_eps: 0.2
norm_adv: True
max_grad_norm: 0.5
v_coef: 0.5
entropy_coef: 0.01
